#index:
#    path: /
#    controller: App\Controller\DefaultController::index

validator:
    path: /validator
    controller: App\Controller\Validator::index
    
test:
    path: /test
    controller: App\Controller\Test::index